import fs from "node:fs";
import path from "node:path";
import { guardHome } from "./paths.js";
import { listRuns, parseRunLog, renderTimeline } from "./replay.js";
import { listBlocks } from "./store.js";
import { estSavedFromWindow } from "./estSaved.js";

/**
 * Incident report: a shareable Markdown post-mortem of one runaway run —
 * the evidence chain a user shows their team (or you post online).
 * Local data only: run logs + block records, no network.
 */

export function incidentDir(): string {
  return path.join(guardHome(), "incidents");
}

export function buildIncidentMarkdown(runId: string, now = Date.now()): string | null {
  const dir = path.join(guardHome(), "runs", runId);
  const reportPath = path.join(dir, "report.json");
  const events = parseRunLog(runId);
  if (!fs.existsSync(reportPath) && events.length === 0) return null;

  let report: Record<string, unknown> = {};
  try {
    report = JSON.parse(fs.readFileSync(reportPath, "utf8")) as Record<string, unknown>;
  } catch {
    /* partial is fine */
  }
  const blocks = listBlocks(200).filter((b) => b.reason !== null || String(b.session_id).startsWith("run-"));

  const blocksList = (report["blocks"] as Array<{ kind: string; tool: string; message: string }> | undefined) ?? [];
  const firstKind = blocksList[0]?.kind ?? (report["endReason"] as string | undefined) ?? "unknown";
  const estSaved = estSavedFromWindow(listBlocks(500).map((b) => ({ kind: b.kind, n: 1 })));

  const lines: string[] = [];
  lines.push(`# Incident report — runaway agent caught by agent-guard`, ``);
  lines.push(`- **run**: \`${runId}\``);
  lines.push(`- **generated**: ${new Date(now).toISOString()}`);
  if (report["command"]) lines.push(`- **agent**: \`${(report["command"] as string[]).join(" ")}\``);
  lines.push(`- **outcome**: ${report["endReason"] ?? "?"} · ${report["toolCalls"] ?? "?"} tool calls · ${report["steps"] ?? "?"} steps`);
  lines.push(``);
  lines.push(`## What happened`);
  lines.push(``);
  lines.push(
    `The agent entered a **${firstKind}** failure pattern. agent-guard detected it after ` +
      `${(report["toolCalls"] as number | undefined) ?? "?"} calls and intervened — ` +
      `instead of silently burning quota until the window was gone.`,
  );
  lines.push(``);
  if (blocksList.length > 0 || blocks.length > 0) {
    lines.push(`## Interventions (with the exact reason the model received)`);
    lines.push(``);
    for (const b of blocksList) {
      lines.push(`### ${b.kind} on \`${b.tool}\``);
      lines.push(``);
      lines.push("```");
      lines.push(b.message);
      lines.push("```");
      lines.push(``);
    }
    const seen = new Set<string>(blocksList.map((b) => `${b.kind}:${b.tool}`));
    for (const b of blocks) {
      const key = `${b.kind}:${b.tool_name}`;
      if (seen.has(key)) continue; // already covered by the run report's own block list
      seen.add(key);
      lines.push(`### ${b.kind} on \`${b.tool_name}\``);
      lines.push(``);
      lines.push("```");
      lines.push(b.reason ?? "");
      lines.push("```");
      lines.push(``);
    }
  }
  lines.push(`## Timeline`);
  lines.push(``);
  lines.push("```");
  lines.push(renderTimeline(events));
  lines.push("```");
  lines.push(``);
  lines.push(`## Impact`);
  lines.push(``);
  lines.push(`- blocks this run: **${blocksList.length}**`);
  lines.push(`- estimated requests saved (heuristic, all-time): **~${estSaved}**`);
  if (typeof report["durationMs"] === "number") lines.push(`- run duration: ${Math.round((report["durationMs"] as number) / 1000)}s`);
  lines.push(`- full machine-readable report: \`${reportPath}\``);
  lines.push(``);
  lines.push(`---`);
  lines.push(`_generated by agent-guard — local data only, nothing left this machine_`);
  return lines.join("\n");
}

export function writeIncident(runId: string, now = Date.now()): { path: string; markdown: string } | null {
  const md = buildIncidentMarkdown(runId, now);
  if (md === null) return null;
  const dir = incidentDir();
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${runId}.md`);
  fs.writeFileSync(file, md, "utf8");
  return { path: file, markdown: md };
}

export function latestRunId(): string | null {
  return listRuns()[0]?.runId ?? null;
}
